# Generated by Django 5.0.7 on 2024-08-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haberler',
            name='slug',
        ),
        migrations.AlterField(
            model_name='haberler',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='haberler',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
