# Generated by Django 5.0.7 on 2024-08-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0002_remove_haberler_slug_alter_haberler_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haberler',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/'),
        ),
    ]
