# Generated by Django 5.0.7 on 2024-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0003_alter_haberler_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='extraimg1',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg2',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg3',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg4',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg5',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg6',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg7',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg8',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
    ]
