# Generated by Django 5.0.7 on 2024-08-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0004_blog_extraimg1_blog_extraimg2_blog_extraimg3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='extraimg1',
            new_name='extraimg',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg3',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg4',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg5',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg6',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg7',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='extraimg8',
        ),
    ]
