# Generated by Django 5.0.7 on 2024-08-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0005_rename_extraimg1_blog_extraimg_remove_blog_extraimg2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='extraimg',
            new_name='extraimg1',
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg2',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg3',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg4',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg5',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg6',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg7',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AddField(
            model_name='blog',
            name='extraimg8',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
    ]
