# Generated by Django 5.0.7 on 2024-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0007_haberler_extraimg1_haberler_extraimg2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
    ]
