# Generated by Django 5.0.7 on 2024-08-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0008_blog_image1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image1',
        ),
        migrations.AddField(
            model_name='haberler',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='dimg'),
        ),
    ]
