# Generated by Django 5.0.7 on 2024-08-05 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0009_remove_blog_image1_haberler_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='entegrasyon',
            name='anadolu_yakasi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entegrasyon',
            name='avrupa_yakasi',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='entegrasyon',
            name='image',
            field=models.ImageField(default=1, upload_to='dimg'),
            preserve_default=False,
        ),
    ]
