# Generated by Django 5.0.7 on 2024-08-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0011_remove_settings_entegrasyonimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='anasayfaimg',
            field=models.FileField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footerlogo1',
            field=models.FileField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='footerlogo2',
            field=models.FileField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo1',
            field=models.FileField(blank=True, null=True, upload_to='dimg'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='logo2',
            field=models.FileField(blank=True, null=True, upload_to='dimg'),
        ),
    ]
