# Generated by Django 5.0.7 on 2024-08-09 07:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tcore', '0012_alter_settings_anasayfaimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
